// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/sftp.proto

package sftp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExportService_ExportDaily_FullMethodName                 = "/export.ExportService/ExportDaily"
	ExportService_Export30Min_FullMethodName                 = "/export.ExportService/Export30Min"
	ExportService_ExportAllReport_FullMethodName             = "/export.ExportService/ExportAllReport"
	ExportService_ExportByLocationID_FullMethodName          = "/export.ExportService/ExportByLocationID"
	ExportService_Export30MinByLocationID_FullMethodName     = "/export.ExportService/Export30MinByLocationID"
	ExportService_ExportAllReportByLocationID_FullMethodName = "/export.ExportService/ExportAllReportByLocationID"
	ExportService_UploadAllPendingFiles_FullMethodName       = "/export.ExportService/UploadAllPendingFiles"
	ExportService_HealthCheck_FullMethodName                 = "/export.ExportService/HealthCheck"
)

// ExportServiceClient is the client API for ExportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Export service definition
type ExportServiceClient interface {
	// Export daily reports for all locations
	ExportDaily(ctx context.Context, in *ExportDailyRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Export 30-minute cumulative reports for all locations
	Export30Min(ctx context.Context, in *Export30MinRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Export all reports (daily + 30min windows) for all locations
	ExportAllReport(ctx context.Context, in *ExportAllReportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Export daily report for specific location
	ExportByLocationID(ctx context.Context, in *ExportByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Export 30-minute cumulative report for specific location
	Export30MinByLocationID(ctx context.Context, in *Export30MinByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Export all reports for specific location
	ExportAllReportByLocationID(ctx context.Context, in *ExportAllReportByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Upload all pending upload
	UploadAllPendingFiles(ctx context.Context, in *UploadAllPendingFilesRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// HealthCheck
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type exportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExportServiceClient(cc grpc.ClientConnInterface) ExportServiceClient {
	return &exportServiceClient{cc}
}

func (c *exportServiceClient) ExportDaily(ctx context.Context, in *ExportDailyRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_ExportDaily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) Export30Min(ctx context.Context, in *Export30MinRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_Export30Min_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) ExportAllReport(ctx context.Context, in *ExportAllReportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_ExportAllReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) ExportByLocationID(ctx context.Context, in *ExportByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_ExportByLocationID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) Export30MinByLocationID(ctx context.Context, in *Export30MinByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_Export30MinByLocationID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) ExportAllReportByLocationID(ctx context.Context, in *ExportAllReportByLocationIDRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_ExportAllReportByLocationID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) UploadAllPendingFiles(ctx context.Context, in *UploadAllPendingFilesRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, ExportService_UploadAllPendingFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ExportService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportServiceServer is the server API for ExportService service.
// All implementations must embed UnimplementedExportServiceServer
// for forward compatibility.
//
// Export service definition
type ExportServiceServer interface {
	// Export daily reports for all locations
	ExportDaily(context.Context, *ExportDailyRequest) (*ExportResponse, error)
	// Export 30-minute cumulative reports for all locations
	Export30Min(context.Context, *Export30MinRequest) (*ExportResponse, error)
	// Export all reports (daily + 30min windows) for all locations
	ExportAllReport(context.Context, *ExportAllReportRequest) (*ExportResponse, error)
	// Export daily report for specific location
	ExportByLocationID(context.Context, *ExportByLocationIDRequest) (*ExportResponse, error)
	// Export 30-minute cumulative report for specific location
	Export30MinByLocationID(context.Context, *Export30MinByLocationIDRequest) (*ExportResponse, error)
	// Export all reports for specific location
	ExportAllReportByLocationID(context.Context, *ExportAllReportByLocationIDRequest) (*ExportResponse, error)
	// Upload all pending upload
	UploadAllPendingFiles(context.Context, *UploadAllPendingFilesRequest) (*ExportResponse, error)
	// HealthCheck
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedExportServiceServer()
}

// UnimplementedExportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExportServiceServer struct{}

func (UnimplementedExportServiceServer) ExportDaily(context.Context, *ExportDailyRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportDaily not implemented")
}
func (UnimplementedExportServiceServer) Export30Min(context.Context, *Export30MinRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export30Min not implemented")
}
func (UnimplementedExportServiceServer) ExportAllReport(context.Context, *ExportAllReportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportAllReport not implemented")
}
func (UnimplementedExportServiceServer) ExportByLocationID(context.Context, *ExportByLocationIDRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportByLocationID not implemented")
}
func (UnimplementedExportServiceServer) Export30MinByLocationID(context.Context, *Export30MinByLocationIDRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export30MinByLocationID not implemented")
}
func (UnimplementedExportServiceServer) ExportAllReportByLocationID(context.Context, *ExportAllReportByLocationIDRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportAllReportByLocationID not implemented")
}
func (UnimplementedExportServiceServer) UploadAllPendingFiles(context.Context, *UploadAllPendingFilesRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadAllPendingFiles not implemented")
}
func (UnimplementedExportServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedExportServiceServer) mustEmbedUnimplementedExportServiceServer() {}
func (UnimplementedExportServiceServer) testEmbeddedByValue()                       {}

// UnsafeExportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExportServiceServer will
// result in compilation errors.
type UnsafeExportServiceServer interface {
	mustEmbedUnimplementedExportServiceServer()
}

func RegisterExportServiceServer(s grpc.ServiceRegistrar, srv ExportServiceServer) {
	// If the following call pancis, it indicates UnimplementedExportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExportService_ServiceDesc, srv)
}

func _ExportService_ExportDaily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDailyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).ExportDaily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_ExportDaily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).ExportDaily(ctx, req.(*ExportDailyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_Export30Min_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Export30MinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).Export30Min(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_Export30Min_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).Export30Min(ctx, req.(*Export30MinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_ExportAllReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportAllReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).ExportAllReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_ExportAllReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).ExportAllReport(ctx, req.(*ExportAllReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_ExportByLocationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportByLocationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).ExportByLocationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_ExportByLocationID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).ExportByLocationID(ctx, req.(*ExportByLocationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_Export30MinByLocationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Export30MinByLocationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).Export30MinByLocationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_Export30MinByLocationID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).Export30MinByLocationID(ctx, req.(*Export30MinByLocationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_ExportAllReportByLocationID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportAllReportByLocationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).ExportAllReportByLocationID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_ExportAllReportByLocationID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).ExportAllReportByLocationID(ctx, req.(*ExportAllReportByLocationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_UploadAllPendingFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAllPendingFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).UploadAllPendingFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_UploadAllPendingFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).UploadAllPendingFiles(ctx, req.(*UploadAllPendingFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExportService_ServiceDesc is the grpc.ServiceDesc for ExportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "export.ExportService",
	HandlerType: (*ExportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportDaily",
			Handler:    _ExportService_ExportDaily_Handler,
		},
		{
			MethodName: "Export30Min",
			Handler:    _ExportService_Export30Min_Handler,
		},
		{
			MethodName: "ExportAllReport",
			Handler:    _ExportService_ExportAllReport_Handler,
		},
		{
			MethodName: "ExportByLocationID",
			Handler:    _ExportService_ExportByLocationID_Handler,
		},
		{
			MethodName: "Export30MinByLocationID",
			Handler:    _ExportService_Export30MinByLocationID_Handler,
		},
		{
			MethodName: "ExportAllReportByLocationID",
			Handler:    _ExportService_ExportAllReportByLocationID_Handler,
		},
		{
			MethodName: "UploadAllPendingFiles",
			Handler:    _ExportService_UploadAllPendingFiles_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ExportService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sftp.proto",
}
