// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/sftp.proto

package sftp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type ExportDailyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDailyRequest) Reset() {
	*x = ExportDailyRequest{}
	mi := &file_proto_sftp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDailyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDailyRequest) ProtoMessage() {}

func (x *ExportDailyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDailyRequest.ProtoReflect.Descriptor instead.
func (*ExportDailyRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{0}
}

func (x *ExportDailyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportDailyRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Export30MinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DateTime      string                 `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Export30MinRequest) Reset() {
	*x = Export30MinRequest{}
	mi := &file_proto_sftp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Export30MinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Export30MinRequest) ProtoMessage() {}

func (x *Export30MinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Export30MinRequest.ProtoReflect.Descriptor instead.
func (*Export30MinRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{1}
}

func (x *Export30MinRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Export30MinRequest) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

type ExportAllReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAllReportRequest) Reset() {
	*x = ExportAllReportRequest{}
	mi := &file_proto_sftp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAllReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAllReportRequest) ProtoMessage() {}

func (x *ExportAllReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAllReportRequest.ProtoReflect.Descriptor instead.
func (*ExportAllReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{2}
}

func (x *ExportAllReportRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportAllReportRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ExportByLocationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportByLocationIDRequest) Reset() {
	*x = ExportByLocationIDRequest{}
	mi := &file_proto_sftp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportByLocationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportByLocationIDRequest) ProtoMessage() {}

func (x *ExportByLocationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportByLocationIDRequest.ProtoReflect.Descriptor instead.
func (*ExportByLocationIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{3}
}

func (x *ExportByLocationIDRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportByLocationIDRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ExportByLocationIDRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Export30MinByLocationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	DateTime      string                 `protobuf:"bytes,3,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Export30MinByLocationIDRequest) Reset() {
	*x = Export30MinByLocationIDRequest{}
	mi := &file_proto_sftp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Export30MinByLocationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Export30MinByLocationIDRequest) ProtoMessage() {}

func (x *Export30MinByLocationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Export30MinByLocationIDRequest.ProtoReflect.Descriptor instead.
func (*Export30MinByLocationIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{4}
}

func (x *Export30MinByLocationIDRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Export30MinByLocationIDRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Export30MinByLocationIDRequest) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

type ExportAllReportByLocationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportAllReportByLocationIDRequest) Reset() {
	*x = ExportAllReportByLocationIDRequest{}
	mi := &file_proto_sftp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportAllReportByLocationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportAllReportByLocationIDRequest) ProtoMessage() {}

func (x *ExportAllReportByLocationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportAllReportByLocationIDRequest.ProtoReflect.Descriptor instead.
func (*ExportAllReportByLocationIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{5}
}

func (x *ExportAllReportByLocationIDRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportAllReportByLocationIDRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ExportAllReportByLocationIDRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Response messages
type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *ExportStats           `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_proto_sftp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{6}
}

func (x *ExportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExportResponse) GetStats() *ExportStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ExportStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalLocations     int32                  `protobuf:"varint,1,opt,name=total_locations,json=totalLocations,proto3" json:"total_locations,omitempty"`
	ProcessedLocations int32                  `protobuf:"varint,2,opt,name=processed_locations,json=processedLocations,proto3" json:"processed_locations,omitempty"`
	FailedLocations    int32                  `protobuf:"varint,3,opt,name=failed_locations,json=failedLocations,proto3" json:"failed_locations,omitempty"`
	TotalRecords       int32                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	LocationStats      []*LocationStats       `protobuf:"bytes,5,rep,name=location_stats,json=locationStats,proto3" json:"location_stats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExportStats) Reset() {
	*x = ExportStats{}
	mi := &file_proto_sftp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportStats) ProtoMessage() {}

func (x *ExportStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportStats.ProtoReflect.Descriptor instead.
func (*ExportStats) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{7}
}

func (x *ExportStats) GetTotalLocations() int32 {
	if x != nil {
		return x.TotalLocations
	}
	return 0
}

func (x *ExportStats) GetProcessedLocations() int32 {
	if x != nil {
		return x.ProcessedLocations
	}
	return 0
}

func (x *ExportStats) GetFailedLocations() int32 {
	if x != nil {
		return x.FailedLocations
	}
	return 0
}

func (x *ExportStats) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *ExportStats) GetLocationStats() []*LocationStats {
	if x != nil {
		return x.LocationStats
	}
	return nil
}

type LocationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	LocationCode  string                 `protobuf:"bytes,2,opt,name=location_code,json=locationCode,proto3" json:"location_code,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DailyRecords  int32                  `protobuf:"varint,5,opt,name=daily_records,json=dailyRecords,proto3" json:"daily_records,omitempty"`
	WindowRecords int32                  `protobuf:"varint,6,opt,name=window_records,json=windowRecords,proto3" json:"window_records,omitempty"`
	TotalWindows  int32                  `protobuf:"varint,7,opt,name=total_windows,json=totalWindows,proto3" json:"total_windows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationStats) Reset() {
	*x = LocationStats{}
	mi := &file_proto_sftp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationStats) ProtoMessage() {}

func (x *LocationStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationStats.ProtoReflect.Descriptor instead.
func (*LocationStats) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{8}
}

func (x *LocationStats) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *LocationStats) GetLocationCode() string {
	if x != nil {
		return x.LocationCode
	}
	return ""
}

func (x *LocationStats) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LocationStats) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LocationStats) GetDailyRecords() int32 {
	if x != nil {
		return x.DailyRecords
	}
	return 0
}

func (x *LocationStats) GetWindowRecords() int32 {
	if x != nil {
		return x.WindowRecords
	}
	return 0
}

func (x *LocationStats) GetTotalWindows() int32 {
	if x != nil {
		return x.TotalWindows
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_sftp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_sftp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sftp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_sftp_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sftp_proto protoreflect.FileDescriptor

const file_proto_sftp_proto_rawDesc = "" +
	"\n" +
	"\x10proto/sftp.proto\x12\x06export\"E\n" +
	"\x12ExportDailyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"N\n" +
	"\x12Export30MinRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdate_time\x18\x02 \x01(\tR\bdateTime\"I\n" +
	"\x16ExportAllReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"m\n" +
	"\x19ExportByLocationIDRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"{\n" +
	"\x1eExport30MinByLocationIDRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tdate_time\x18\x03 \x01(\tR\bdateTime\"v\n" +
	"\"ExportAllReportByLocationIDRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"o\n" +
	"\x0eExportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05stats\x18\x03 \x01(\v2\x13.export.ExportStatsR\x05stats\"\xf5\x01\n" +
	"\vExportStats\x12'\n" +
	"\x0ftotal_locations\x18\x01 \x01(\x05R\x0etotalLocations\x12/\n" +
	"\x13processed_locations\x18\x02 \x01(\x05R\x12processedLocations\x12)\n" +
	"\x10failed_locations\x18\x03 \x01(\x05R\x0ffailedLocations\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x05R\ftotalRecords\x12<\n" +
	"\x0elocation_stats\x18\x05 \x03(\v2\x15.export.LocationStatsR\rlocationStats\"\x85\x02\n" +
	"\rLocationStats\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12#\n" +
	"\rlocation_code\x18\x02 \x01(\tR\flocationCode\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12#\n" +
	"\rdaily_records\x18\x05 \x01(\x05R\fdailyRecords\x12%\n" +
	"\x0ewindow_records\x18\x06 \x01(\x05R\rwindowRecords\x12#\n" +
	"\rtotal_windows\x18\a \x01(\x05R\ftotalWindows\"\x14\n" +
	"\x12HealthCheckRequest\"?\n" +
	"\x13HealthCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb7\x04\n" +
	"\rExportService\x12A\n" +
	"\vExportDaily\x12\x1a.export.ExportDailyRequest\x1a\x16.export.ExportResponse\x12A\n" +
	"\vExport30Min\x12\x1a.export.Export30MinRequest\x1a\x16.export.ExportResponse\x12I\n" +
	"\x0fExportAllReport\x12\x1e.export.ExportAllReportRequest\x1a\x16.export.ExportResponse\x12O\n" +
	"\x12ExportByLocationID\x12!.export.ExportByLocationIDRequest\x1a\x16.export.ExportResponse\x12Y\n" +
	"\x17Export30MinByLocationID\x12&.export.Export30MinByLocationIDRequest\x1a\x16.export.ExportResponse\x12a\n" +
	"\x1bExportAllReportByLocationID\x12*.export.ExportAllReportByLocationIDRequest\x1a\x16.export.ExportResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.export.HealthCheckRequest\x1a\x1b.export.HealthCheckResponseB\fZ\n" +
	"proto/sftpb\x06proto3"

var (
	file_proto_sftp_proto_rawDescOnce sync.Once
	file_proto_sftp_proto_rawDescData []byte
)

func file_proto_sftp_proto_rawDescGZIP() []byte {
	file_proto_sftp_proto_rawDescOnce.Do(func() {
		file_proto_sftp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sftp_proto_rawDesc), len(file_proto_sftp_proto_rawDesc)))
	})
	return file_proto_sftp_proto_rawDescData
}

var file_proto_sftp_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_sftp_proto_goTypes = []any{
	(*ExportDailyRequest)(nil),                 // 0: export.ExportDailyRequest
	(*Export30MinRequest)(nil),                 // 1: export.Export30MinRequest
	(*ExportAllReportRequest)(nil),             // 2: export.ExportAllReportRequest
	(*ExportByLocationIDRequest)(nil),          // 3: export.ExportByLocationIDRequest
	(*Export30MinByLocationIDRequest)(nil),     // 4: export.Export30MinByLocationIDRequest
	(*ExportAllReportByLocationIDRequest)(nil), // 5: export.ExportAllReportByLocationIDRequest
	(*ExportResponse)(nil),                     // 6: export.ExportResponse
	(*ExportStats)(nil),                        // 7: export.ExportStats
	(*LocationStats)(nil),                      // 8: export.LocationStats
	(*HealthCheckRequest)(nil),                 // 9: export.HealthCheckRequest
	(*HealthCheckResponse)(nil),                // 10: export.HealthCheckResponse
}
var file_proto_sftp_proto_depIdxs = []int32{
	7,  // 0: export.ExportResponse.stats:type_name -> export.ExportStats
	8,  // 1: export.ExportStats.location_stats:type_name -> export.LocationStats
	0,  // 2: export.ExportService.ExportDaily:input_type -> export.ExportDailyRequest
	1,  // 3: export.ExportService.Export30Min:input_type -> export.Export30MinRequest
	2,  // 4: export.ExportService.ExportAllReport:input_type -> export.ExportAllReportRequest
	3,  // 5: export.ExportService.ExportByLocationID:input_type -> export.ExportByLocationIDRequest
	4,  // 6: export.ExportService.Export30MinByLocationID:input_type -> export.Export30MinByLocationIDRequest
	5,  // 7: export.ExportService.ExportAllReportByLocationID:input_type -> export.ExportAllReportByLocationIDRequest
	9,  // 8: export.ExportService.HealthCheck:input_type -> export.HealthCheckRequest
	6,  // 9: export.ExportService.ExportDaily:output_type -> export.ExportResponse
	6,  // 10: export.ExportService.Export30Min:output_type -> export.ExportResponse
	6,  // 11: export.ExportService.ExportAllReport:output_type -> export.ExportResponse
	6,  // 12: export.ExportService.ExportByLocationID:output_type -> export.ExportResponse
	6,  // 13: export.ExportService.Export30MinByLocationID:output_type -> export.ExportResponse
	6,  // 14: export.ExportService.ExportAllReportByLocationID:output_type -> export.ExportResponse
	10, // 15: export.ExportService.HealthCheck:output_type -> export.HealthCheckResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_sftp_proto_init() }
func file_proto_sftp_proto_init() {
	if File_proto_sftp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sftp_proto_rawDesc), len(file_proto_sftp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sftp_proto_goTypes,
		DependencyIndexes: file_proto_sftp_proto_depIdxs,
		MessageInfos:      file_proto_sftp_proto_msgTypes,
	}.Build()
	File_proto_sftp_proto = out.File
	file_proto_sftp_proto_goTypes = nil
	file_proto_sftp_proto_depIdxs = nil
}
